/*******************************************************************************
  o2_core_views.sql
  ─────────────────────────────────────────────────────────────────────────────
  PURPOSE
    • Provide the **production-ready view** `core_energy.v_model_wide`.
    • v_model_wide is a *curated* subset of v_series_wide, suitable for
      front-office models, dashboards, and any object that must not break when
      experimental series appear or disappear.

  LAYERING RATIONALE
    ┌─────────────────────────┐
    │ core_energy.v_series_wide│  ← AUTO-generated by
    │  (grand universe)       │     scripts/load_dim_series_from_csv.py
    └────────────┬────────────┘
                 │ (select / transform / derive)
    ┌────────────▼────────────┐
    │ core_energy.v_model_wide│  ← THIS VIEW
    │  (production subset)    │
    └─────────────────────────┘

    * v_series_wide = every `model_col` you ingest.  Great for ad-hoc analysis.
    * v_model_wide  = only columns that have stable definitions, final units,
      and governance sign-off.  **All production code must read from this view.**

  HOW TO USE / EXTEND
  ───────────────────
    1. **Promoting a new series to production**
         a. Ensure it is in dim_series.csv and appears in v_series_wide.
         b. Edit THIS FILE: add the column to the SELECT list below, applying
            any unit conversion, alias aggregation, or NULL-guard logic.
         c. Commit, run migrations (or rebuild container), and the series is
            instantly available to all downstream objects.

    2. **Unit conversions / derived metrics**
         Replace the simple “SELECT *” with explicit expressions, e.g.

           SELECT
               date,
               us_crude_exports                          AS us_crude_exports_kbd,
               ending_commercial_crude_stocks / 1000.0   AS ending_commercial_crude_stocks_mb,
               (ending_total_crude_stocks
                - ending_spr_crude_stocks)               AS ending_commercial_plus_product
           FROM core_energy.v_series_wide

    3. **Governance reminder**
         • Keep this file under version control.
         • Update the project’s “Data Layers” doc when you change the columns.
         • All new production views (e.g., product balances) should live in
           their own o#.sql files but SELECT from **v_model_wide**, *not* from
           v_series_wide.

*******************************************************************************/

CREATE OR REPLACE VIEW core_energy.v_model_wide AS
SELECT *
FROM   core_energy.v_series_wide;
